# Generated by Django 3.0.6 on 2020-06-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='state',
            field=models.CharField(choices=[('1', 'Published'), ('0', 'Unpublished')], default='1', max_length=1),
        ),
    ]
