# Generated by Django 3.0.6 on 2020-06-04 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Topic',
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='category',
            new_name='topic',
        ),
    ]
