# Generated by Django 3.0.6 on 2020-06-04 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200604_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 22, 30, 13, 855509), editable=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 22, 30, 13, 855509), editable=False),
        ),
    ]
