# Generated by Django 3.0.6 on 2020-06-16 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('courses', '0016_auto_20200614_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='profiles.UserProfile'),
        ),
    ]
