# Generated by Django 3.0.6 on 2020-06-04 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='chapter',
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
